# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180710_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='question',
            field=models.TextField(default='write question'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='question tag', max_length=50),
        ),
    ]
